version: "3.8"

services:

  mysql:
    image: mysql:8
    container_name: mysql-strapi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword123
      MYSQL_DATABASE: iotwebsite_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  strapi:
    build: ./cms
    container_name: strapi
    restart: always
    expose:
      - "1337"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0          # ⭐ เพิ่มอันนี้
      PORT: 1337             # ⭐ เพิ่มอันนี้
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: iotwebsite_db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: strongpassword123
      APP_KEYS: 966a40e6a2aa8686ac64e65080dc0e8b192ce0855ff2a7ecafc4ec65211e8fbc,34933de2a6e9e31f1779e291d74af7a84271a42e63094534c6166bb8ca5216a3
      API_TOKEN_SALT: 880f766da702829f33aad2554368bb5106b0a61d1d46f1c0982921c7ce5ad147
      ADMIN_JWT_SECRET: 8ac915a4c46bdffd7c0f68951c3352d5991a3bc659ffbb8b17b1f210488f8c9f
      JWT_SECRET: 34933de2a6e9e31f1779e291d74af7a84271a42e63094534c6166bb8ca5216a3
    volumes:
      - ./cms/public/uploads:/app/public/uploads

  nuxt:
    build: ./IoTwebsite
    container_name: nuxt
    restart: always
    expose:
      - "3000"
    environment:
      - HOST=0.0.0.0    # ⭐ เพิ่มบรรทัดนี้
      - PORT=3000       # ⭐ เพิ่มบรรทัดนี้
    depends_on:
      - strapi

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt
      - strapi

volumes:
  mysql_data: