events {}

http {

  server {

    listen 80;

    location / {
      proxy_pass http://nuxt:3000;
    }

    location /api {
      proxy_pass http://strapi:1337;
    }

    location /uploads {
      proxy_pass http://strapi:1337;
    }

    location /admin {
      proxy_pass http://strapi:1337;
    }

  }

}