events {}

http {

  server {

    listen 80;
    server_name 67011430.consolutechcloud.com;

    location / {
      proxy_pass http://nuxt:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location /admin/ {
      proxy_pass http://strapi:1337/admin/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/ {
      proxy_pass http://strapi:1337/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
      proxy_pass http://strapi:1337/uploads/;
    }

  }

}