events {}

http {

  server {

    listen 80;
    server_name 67011430.consolutechcloud.com;

    # Nuxt frontend
    location / {
      proxy_pass http://nuxt:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # Strapi Admin
    location /admin {
      proxy_pass http://strapi:1337;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Strapi API
    location /api {
      proxy_pass http://strapi:1337;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Strapi uploads
    location /uploads {
      proxy_pass http://strapi:1337;
    }

    # ⭐ สำคัญสำหรับ plugin routes
    location /content-manager {
      proxy_pass http://strapi:1337;
    }

    location /content-type-builder {
      proxy_pass http://strapi:1337;
    }

    location /users-permissions {
      proxy_pass http://strapi:1337;
    }

    location /upload {
      proxy_pass http://strapi:1337;
    }

  }

}